GET http://localhost:4444/employees

###
GET http://localhost:4444/employees/2

###
POST http://localhost:4444/employees
Content-Type: application/json

{
    "firstname":"Clark",
    "lastname":"Kent"
}

###
PUT http://localhost:4444/employees
Content-Type: application/json

{
    "id":2,
    "firstname":"Ezio",
    "lastname":"Auditore"
}

###
DELETE  http://localhost:4444/employees
Content-Type: application/json

{
    "id":4
}